---
title: "Data Import"
output: github_document
---


```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## read in some data

read in the litters dataset


```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## take a look at the data
printing in the console
```{r}
litters_df
```
```{r}
head(litters_df)
```

```{r}
skimr::skim(litters_df)
```
```{r}
litters_df = read_csv("./data/FAS_litters.csv",skip=10,col_names=FALSE)
```

```{r}
litters_df = read_csv("./data/FAS_litters.csv",na = c("","NA",".",999))
```
check out "?read_csv()" for more information.

## other file formats
read in an excel file.
```{r}
mlb_df = read_excel("./data/mlb11.xlsx",range=("A1:F7"))
mlb_df
```

read in an sas file
```{r}
pulse_df=read_sas("./data/public_pulse_data.sas7bdat")
pulse_df = janitor::clean_names(pulse_df)
pulse_df
```

## comparison with base r
what about 'read.csv'...? (no)

```{r}
litter_base = read.csv("data/FAS_litters.csv")
litter_readr = read_csv("data/FAS_litters.csv")
litter_base
litter_readr
```
## exporting data
export mlb sub-table
```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```













