---
title: "Tidy Data"
output: github_document
---


```{r setup}
library(tidyverse)
```

## 'pivot longer'
use pulse data
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
pulse_data
```

wide format to long format
```{r}
pulse_data_tidy=
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to="bdi"
  )
pulse_data_tidy
```


rewrite, combine, and extend (to add a mutate)
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to="bdi"
  ) %>% 
relocate(id,visit) %>% 
  mutate(visit=recode(visit,"bl"="00m"))

pulse_data
```

## 'pivot_wider'

make up some data

```{r}
analysis_results=
  tibble(
    group=c("treatment","treatment","placebo","placebo"),
    time=c("pre","post","pre","post"),
    mean=c(4,8,3.5,4)
  )

analysis_results %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
analysis_results
```



## Binding rows

use the LotR data
first step: import each table
```{r}
fellowship_ring=
  readxl::read_excel("./data/LotR_Words.xlsx",range="B3:D6") %>% 
  mutate(movie="fellowship_ring")

two_towers=
  readxl::read_excel("./data/LotR_Words.xlsx",range="F3:H6") %>% 
  mutate(movie="two_towers")

return_king=
  readxl::read_excel("./data/LotR_Words.xlsx",range="J3:L6") %>% 
  mutate(movie="return_king")

```

bind all rows together

```{r}
lotr_tidy=
  bind_rows(fellowship_ring, two_towers,return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to="gender",
    values_to="words"
  )
```


## joining dataset
import and clean dataset
```{r}
pups_df=
  read_csv("./data/FAS_pups.csv",show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  mutate(sex=recode(sex,'1'="male",'2'="female"))

pups_df

litters_df=
  read_csv("./data/FAS_litters.csv",show_col_types = FALSE) %>% 
  janitor::clean_names() %>% 
  relocate(litter_number) %>% 
  separate(group,into=c("dose","day_of_tx"),sep=3)

litters_df
```

next up, time to join them

```{r}
fas_df=
  left_join(pups_df,litters_df,by="litter_number") %>% 
  arrange(litter_number) %>% 
  relocate(litter_number,dose,day_of_tx)
  
fas_df
```











